---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: website
    labels:
        app: beginner.codes-website
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 50%
    selector:
        matchLabels:
            app: beginner.codes-website
            tier: frontend
    replicas: 2
    template:
        metadata:
            labels:
                app: beginner.codes-website
                tier: frontend
        spec:
            topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                  matchLabels:
                      app: beginner.codes-website
            containers:
              - name: fastapi-site
                image: zzmmrmn/beginner.codes-website:<IMAGE_VERSION>
                ports:
                  - containerPort: 8000
                resources:
                    requests:
                        cpu: 100m
