---
apiVersion: v1
kind: Service
metadata:
    name: beginner.codes-website
    labels:
        app: beginner.codes-website
        tier: frontend
spec:
    type: NodePort
    ports:
      - port: 8000
        name: http
    selector:
        app: beginner.codes-website
        tier: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: beginner.codes-website
    labels:
        app: beginner.codes-website
    annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/limit-rpm: "100"
        cert-manager.io/cluster-issuer: "letsencrypt"
spec:
    tls:
      - hosts:
        - beginner.codes
        secretName: beginner.codes-cert
    rules:
      - host: beginner.codes
        http:
            paths:
              - backend:
                    serviceName: beginner.codes-website
                    servicePort: 8000
